live_config_reload = true

[font]
size = 16.0
# use_thin_strokes = true

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = false
# opacity = 0.85

[window.padding]
x = 18
y = 16
