# tasks/homebrew/install_homebrew_casks.yml

- name: Install homebrew casks
  vars:
    brew_cask_packages_install: []
    brew_cask_packages_uninstall: []

  block:
    - name: Set HomeBrew path
      ansible.builtin.set_fact:
        homebrew_path: /usr/local/bin/brew
      when: ansible_architecture != "arm64"

    - name: Set HomeBrew path
      ansible.builtin.set_fact:
        homebrew_path: "/opt/homebrew/bin/brew"
      when: ansible_architecture == "arm64"

    - name: Ensuring Homebrew Is Installed
      ansible.builtin.stat:
        path: "{{ homebrew_path  }}"
      register: homebrew_check

    - name: Define Homebrew Cask Packages to Install
      ansible.builtin.set_fact:
        brew_cask_packages_install: "{{ brew_cask_packages_install + [item.name] }}"
      loop: "{{ brew_cask_packages }}"
      when: item.state | lower == "present"

    - name: Define Homebrew Cask Packages to Uninstall
      ansible.builtin.set_fact:
        brew_cask_packages_uninstall: "{{ brew_cask_packages_uninstall + [item.name] }}"
      loop: "{{ brew_cask_packages }}"
      when: item.state | lower == "absent"

    # - name: Installing Homebrew Cask Packages
    #   community.general.packaging.os.homebrew_cask:
    #     name: "{{ brew_cask_packages_install }}"
    #     state: present
    #     # name: google-chrome
    #   register: result
    #   until: result is successful
    #   when: homebrew_check.stat.exists
    - name: Installing Homebrew Cask Packages
      become: false
      ansible.builtin.shell:
        cmd: "{{ homebrew_path }} install --cask {{ item.name }}"
      loop: "{{ brew_cask_packages }}"
      when:
        - item.state | lower == 'present'
        - homebrew_check.stat.exists

    - name: Uninstall Homebrew Cask Packages
      become: false
      community.general.packaging.os.homebrew_cask:
        name: "{{ brew_cask_packages_uninstall }}"
        state: absent
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: List installed Homebrew Casks packages
      become: false
      command: "{{ homebrew_path }}/brew list"
      register: installed_packages
      changed_when: False

    - name: Check if specific Cask packages are installed
      become: false
      debug:
        msg: "{{ item }} is installed."
      loop: "{{ brew_cask_packages_install | default([]) }}"
      when:
        - item in installed_packages.stdout_lines
