-- .config/sketchybar/items/widgets/init.lua
require("items.widgets.mic")
require("items.widgets.weather")
require("items.widgets.battery")
require("items.widgets.volume")
require("items.widgets.wifi")
require("items.widgets.cpu")
require("items.widgets.ram")
require("items.widgets.ssd")
-- require("items.widgets.mic")
